name: BUILD

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 18 * * *'

jobs:
  Build:
    strategy:
      matrix:
        repos:
          - utools
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: ./build
        key: build
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
  Upload:
    runs-on: ubuntu-latest
    if: always()
    needs: [Build]
    steps:
      - uses: actions/cache@v3
        with:
          path: ./build
          key: build
      - run: curl ${{secrets.ADDRESS}} -v
      - uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.ADDRESS}}
          webdav_username: ${{secrets.USERNAME}}
          webdav_password: ${{secrets.PASSWORD}}
          webdav_upload_path: "/ArchRepo"
          files: ./build/**
