name: BUILD

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 18 * * *'

jobs:
  Build:
    strategy:
      matrix:
        repos:
          - utools
          - yay-bin
          - jxplorer
          - wps-office
          - v2raya-bin
          - wemeet-bin
          - rime-symbols
          - ttf-wps-fonts
          - mojave-gtk-theme
          - yuzu-mainline-bin
          - rime-cloverpinyin
          - netease-cloud-music
          - visual-studio-code-bin
          - microsoft-edge-stable-bin
          - gnome-shell-extension-vitals
          - intellij-idea-ultimate-edition
          - mcmojave-circle-icon-theme-git
          - gnome-shell-extension-dash-to-panel
          - gnome-shell-extension-clipboard-indicator
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
    - uses: actions/upload-artifact@v2
      with:
        path: ./build/${{ matrix.repos }}/*.pkg.tar.zst
        name: ${{ matrix.repos }}
  UploadToOneDrive:
    runs-on: ubuntu-latest
    if: always()
    needs: [Build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.address}}
          webdav_username: ${{secrets.username}}
          webdav_password: ${{secrets.password}}
          webdav_upload_path: "/ArchRepo"
          files: ${{ steps.download.outputs.download-path }}
