name: BUILD

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 18 * * *'

jobs:
  Build:
    strategy:
      matrix:
        repos:
          - utools
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
    - uses: actions/upload-artifact@v2
      with:
        path: ./build/${{ matrix.repos }}/*.pkg.tar.zst
        name: ${{ matrix.repos }}
  UploadToOneDrive:
    runs-on: ubuntu-latest
    if: always()
    needs: [Build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.ADDRESS}}
          webdav_username: ${{secrets.USERNAME}}
          webdav_password: ${{secrets.PASSWORD}}
          webdav_upload_path: "/ArchRepo"
          files: ${{ steps.download.outputs.download-path }}
