name: BUILD

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '1 */8 * * *'

jobs:
  Build:
    strategy:
      matrix:
        repos: 
          - gnome-shell-extension-clipboard-indicator
          - gnome-shell-extension-dash-to-panel
          - gnome-shell-extension-vitals
          - intellij-idea-ultimate-edition-jre
          - jxplorer
          - mcmojave-circle-icon-theme
          - microsoft-edge-stable-bin
          - mojave-gtk-theme
          - netease-cloud-music
          - rime-cloverpinyin
          - rime-symbols
          - ttf-wps-fonts
          - utools
          - v2raya-bin
          - wemeet-bin
          - wps-office
          - yay-bin
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
    - uses: actions/upload-artifact@v2
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
  UploadToOneDrive:      
    runs-on: ubuntu-latest
    if: always()
    needs: [Build]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        id: download
      - uses: ./create-db-and-upload-action
        with:
          RCLONE_ONEDRIVE_CLIENT_ID: ${{ secrets.RCLONE_ONEDRIVE_CLIENT_ID }}
          RCLONE_ONEDRIVE_CLIENT_SECRET: ${{ secrets.RCLONE_ONEDRIVE_CLIENT_SECRET }}
          RCLONE_ONEDRIVE_REGION: ${{ secrets.RCLONE_ONEDRIVE_REGION }}
          RCLONE_ONEDRIVE_TOKEN: ${{ secrets.RCLONE_ONEDRIVE_TOKEN }}
          RCLONE_ONEDRIVE_DRIVE_ID: ${{ secrets.RCLONE_ONEDRIVE_DRIVE_ID }}
          RCLONE_ONEDRIVE_DRIVE_TYPE: ${{ secrets.RCLONE_ONEDRIVE_DRIVE_TYPE }}
          dest_path: /Public/ArchRepo
          repo_name: xausky
          local_path: ${{ steps.download.outputs.download-path }}
