name: BUILD

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 18 * * *'

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ./build
          key: build-${{env.GITHUB_RUN_NUMBER}}
          restore-keys: |
            build-
      - uses: ./build-aur-action
        with:
          repo-name: mojave-gtk-theme
      - uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.ADDRESS}}
          webdav_username: ${{secrets.USERNAME}}
          webdav_password: ${{secrets.PASSWORD}}
          webdav_upload_path: "/ArchRepo"
          files: ./build/*/*.pkg.tar.zst
