name: BUILD

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 10 * * *'

jobs:
  Build:
    strategy:
      matrix:
        repos:
          - utools
          - yay-bin
          - jxplorer
          - resp-app
          - wps-office
          - v2raya-bin
          - wemeet-bin
          - rime-symbols
          - ttf-wps-fonts
          - mojave-gtk-theme
          - yuzu-mainline-bin
          - rime-cloverpinyin
          - netease-cloud-music
          - visual-studio-code-bin
          - microsoft-edge-stable-bin
          - gnome-shell-extension-vitals
          - intellij-idea-ultimate-edition
          - mcmojave-circle-icon-theme-git
          - gnome-shell-extension-dash-to-panel
          - gnome-shell-extension-clipboard-indicator
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
    - uses: actions/upload-artifact@v2
      with:
        path: ./build/${{ matrix.repos }}/*.pkg.tar.zst
        name: ${{ matrix.repos }}
  UploadToOneDrive:
    runs-on: ubuntu-latest
    if: always()
    needs: [Build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        id: download
      - uses: ./create-db-and-upload-action
        with:
          RCLONE_ONEDRIVE_CLIENT_ID: ${{ secrets.RCLONE_ONEDRIVE_CLIENT_ID }}
          RCLONE_ONEDRIVE_CLIENT_SECRET: ${{ secrets.RCLONE_ONEDRIVE_CLIENT_SECRET }}
          RCLONE_ONEDRIVE_REGION: ${{ secrets.RCLONE_ONEDRIVE_REGION }}
          RCLONE_ONEDRIVE_TOKEN: ${{ secrets.RCLONE_ONEDRIVE_TOKEN }}
          RCLONE_ONEDRIVE_DRIVE_ID: ${{ secrets.RCLONE_ONEDRIVE_DRIVE_ID }}
          RCLONE_ONEDRIVE_DRIVE_TYPE: ${{ secrets.RCLONE_ONEDRIVE_DRIVE_TYPE }}
          dest_path: /Public/ArchRepo
          repo_name: xausky
          local_path: ${{ steps.download.outputs.download-path }}
