name: BUILD

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 18 * * *'

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./build-aur-action
        with:
          repo-name: |
            wemeet-bin
            jxplorer
            yay-bin
            postman-bin
            microsoft-edge-stable-bin
            visual-studio-code-bin
            onlyoffice-bin
            intellij-idea-ultimate-edition
            intellij-idea-ultimate-edition-jre
            com.qq.weixin.deepin
            # com.qq.weixin.work.deepin-x11
      - uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.ADDRESS}}
          webdav_username: ${{secrets.USERNAME}}
          webdav_password: ${{secrets.PASSWORD}}
          webdav_upload_path: "/ArchRepo"
          files: ./dist/**
